function cfg = cs_default_config()
%CS_DEFAULT_CONFIG 压缩感知回波恢复模块的默认配置。
% 输出：
%   cfg.project   传递给现有 GOTCHA BP 工程的覆盖配置。
%   cfg.method    控制 1D/2D 恢复方法是否运行。
%   cfg.compare   控制成像和点目标分析对比。
%   cfg.recovery  恢复算法参数。
%   cfg.data      可选的数据裁剪范围。
%   cfg.output    新模块结果目录配置。

cfg = struct();

% 复用主流程完整 schema，使 csCfg.project 的严格覆盖语义与 main_gotha_bp 一致。
cfg.project = default_config();

cfg.method = struct( ...
    'run1D', true, ...
    'run2D', true);

cfg.compare = struct( ...
    'runImaging', true, ...
    'runPointAnalysis', true, ...
    'failOnPointAnalysisError', false);

cfg.recovery = struct( ...
    'maxIter', 200, ...
    'tol', 1e-4, ...
    'lambda1D', 0.01, ...
    'lambda2D', 0.005, ...
    'useFista', true, ...
    'normalizeInput', true, ...
    'verbose', true);

% 留空时使用完整数据，用于快速调试时可填写索引范围。
cfg.data = struct( ...
    'rangeIndexRange', [], ...
    'azimuthIndexRange', []);

cfg.output = struct( ...
    'resultsDirName', 'results', ...
    'runFolderPrefix', 'run', ...
    'timestampFormat', 'yyyyMMdd_HHmmss');
end
