%% 最小主流程示例
% 通过 userCfg 覆盖主流程配置。
% 默认兼容 GOTCHA；其它数据集请覆盖 general.*。
% 第一次运行建议只改 dataRoot。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(projectRoot);

userCfg = struct();

% 第 1 步：显式指定数据根目录。
userCfg.path = struct( ...
    'dataRoot', 'E:/path/to/your_dataset_root');

% 第 2 步：不是默认 GOTCHA 时，再补数据契约。
% userCfg.general = struct( ...
%     'numDataFiles', 2, ...
%     'dataFilePattern', 'sar_pass_%02d.mat', ...
%     'dataVariableName', 'sarData', ...
%     'dataFieldMap', struct( ...
%         'x', 'platform_x', ...
%         'y', 'platform_y', ...
%         'z', 'platform_z', ...
%         'echo', 'echo_matrix', ...
%         'freq', 'freq_hz'));

% 第 3 步：如需调实验参数，再逐层补字段。
% userCfg.interruption = struct( ...
%     'mode', 'random_gap', ...
%     'numSegments', 5, ...
%     'missingRatio', 0.07, ...
%     'randomSeed', 42);
%
% userCfg.display = struct( ...
%     'showInterruptedEcho', true, ...
%     'showProgress', true);
%
% userCfg.analysis = struct( ...
%     'pointAnaCfg', struct('showFigures', true));

result = main_gotha_bp(userCfg);
% 第 4 步：先看输出目录和 result.image。
disp(result.meta.runOutput.runDir);
