%% 最小主流程示例
% 通过配置覆盖运行 BP 主流程，不要直接修改生产源码。
% 默认数据契约兼容 GOTCHA；如果是其它数据集，请覆盖 general.* 中的数据契约字段。
% 建议第一次运行时只改 dataRoot，先确认主流程能正常出图。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(projectRoot);

userCfg = struct();

% 第 1 步：显式指定数据根目录。
userCfg.path = struct( ...
    'dataRoot', 'E:/path/to/your_dataset_root');

% 第 2 步：如果不是默认 GOTCHA 数据格式，再补数据契约。
% userCfg.general = struct( ...
%     'numDataFiles', 2, ...
%     'dataFilePattern', 'sar_pass_%02d.mat', ...
%     'dataVariableName', 'sarData', ...
%     'dataFieldMap', struct( ...
%         'x', 'platform_x', ...
%         'y', 'platform_y', ...
%         'z', 'platform_z', ...
%         'echo', 'echo_matrix', ...
%         'freq', 'freq_hz'));

% 第 3 步：如需覆盖实验参数，可按字段逐层补充。
% userCfg.interruption = struct( ...
%     'mode', 'random_gap', ...
%     'numSegments', 5, ...
%     'missingRatio', 0.07, ...
%     'randomSeed', 42);
%
% userCfg.display = struct( ...
%     'showInterruptedEcho', true, ...
%     'showProgress', true);
%
% userCfg.analysis = struct( ...
%     'pointAnaCfg', struct('showFigures', true));

result = main_gotha_bp(userCfg);
% 第 4 步：先看输出目录和 result.image，确认主流程已经跑通。
disp(result.meta.runOutput.runDir);
