%% 最小恢复流程示例
% 通过 csCfg 覆盖恢复实验参数，不要直接修改 cs_default_config.m 或 default_config.m。
% 恢复流程复用 csCfg.project 中的主流程数据契约配置。
% 建议先确认 examples/run_bp_minimal.m 能跑通，再运行这里。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(projectRoot);
addpath(fullfile(projectRoot, 'cs_echo_recovery'));

csCfg = struct();

% 第 1 步：通过 csCfg.project 传递主流程配置覆盖。
csCfg.project = struct( ...
    'path', struct('dataRoot', 'E:/path/to/your_dataset_root'));

% 第 2 步：如果不是默认 GOTCHA 数据格式，请通过 csCfg.project.general 覆盖数据契约。
% csCfg.project.general = struct( ...
%     'numDataFiles', 2, ...
%     'dataFilePattern', 'sar_pass_%02d.mat', ...
%     'dataVariableName', 'sarData', ...
%     'dataFieldMap', struct( ...
%         'x', 'platform_x', ...
%         'y', 'platform_y', ...
%         'z', 'platform_z', ...
%         'echo', 'echo_matrix', ...
%         'freq', 'freq_hz'));

% 第 3 步：可选地覆盖间断参数。
% csCfg.project.interruption = struct( ...
%     'mode', 'random_gap', ...
%     'numSegments', 5, ...
%     'missingRatio', 0.1, ...
%     'randomSeed', 42);
%
% 第 4 步：可选地覆盖恢复参数。
% csCfg.recovery = struct( ...
%     'maxIter', 200, ...
%     'lambda1D', 0.01, ...
%     'lambda2D', 0.005);
%
% 第 5 步：可选地只跑一种恢复方法。
% csCfg.method = struct( ...
%     'run1D', true, ...
%     'run2D', false);

result = run_cs_echo_recovery_demo(csCfg);
% 第 6 步：先看恢复输出目录，再比较 original / interrupted / recovered_*。
disp(result.paths.runDir);
