function cfg = bp_validate_config(cfg)
%BP_VALIDATE_CONFIG 校验运行配置。
assert(islogical(cfg.general.useSinglePrecision) && isscalar(cfg.general.useSinglePrecision), ...
    'cfg.general.useSinglePrecision 必须是逻辑标量。');
assert(isnumeric(cfg.general.numDataFiles) && isscalar(cfg.general.numDataFiles) ...
    && cfg.general.numDataFiles >= 1 && mod(cfg.general.numDataFiles, 1) == 0, ...
    'cfg.general.numDataFiles 必须是正整数。');
assert(ischar(cfg.general.dataFilePattern) || isstring(cfg.general.dataFilePattern), ...
    'cfg.general.dataFilePattern 必须是文本。');

assert(cfg.radar.c > 0 && cfg.radar.w0 > 0 && cfg.radar.tau > 0, ...
    'cfg.radar.c、cfg.radar.w0 和 cfg.radar.tau 必须为正值。');
assert(cfg.radar.rangeUpsampleFactor >= 1 && mod(cfg.radar.rangeUpsampleFactor, 1) == 0, ...
    'cfg.radar.rangeUpsampleFactor 必须是不小于 1 的整数。');

assert(cfg.image.numPixels >= 2 && mod(cfg.image.numPixels, 1) == 0, ...
    'cfg.image.numPixels 必须是不小于 2 的整数。');
assert(isnumeric(cfg.image.xLimits) && numel(cfg.image.xLimits) == 2 ...
    && cfg.image.xLimits(1) < cfg.image.xLimits(2), ...
    'cfg.image.xLimits 必须是长度为 2 的递增数值向量。');
assert(isnumeric(cfg.image.yLimits) && numel(cfg.image.yLimits) == 2 ...
    && cfg.image.yLimits(1) < cfg.image.yLimits(2), ...
    'cfg.image.yLimits 必须是长度为 2 的递增数值向量。');

assert(ischar(cfg.interruption.mode) || isstring(cfg.interruption.mode), ...
    'cfg.interruption.mode 必须是文本。');
modeName = char(string(cfg.interruption.mode));
assert(any(strcmp(modeName, {'tail_gap', 'random_gap'})), ...
    'cfg.interruption.mode 必须是 tail_gap 或 random_gap。');
assert(cfg.interruption.numSegments >= 1 && mod(cfg.interruption.numSegments, 1) == 0, ...
    'cfg.interruption.numSegments 必须是正整数。');
assert(cfg.interruption.missingRatio >= 0 && cfg.interruption.missingRatio < 1, ...
    'cfg.interruption.missingRatio 必须满足 0 <= missingRatio < 1。');
assert(isnumeric(cfg.interruption.gapMinMeters) && isscalar(cfg.interruption.gapMinMeters) ...
    && cfg.interruption.gapMinMeters >= 0, ...
    'cfg.interruption.gapMinMeters 必须是非负标量。');
assert(isnumeric(cfg.interruption.gapMaxMeters) && isscalar(cfg.interruption.gapMaxMeters) ...
    && cfg.interruption.gapMaxMeters >= 0, ...
    'cfg.interruption.gapMaxMeters 必须是非负标量。');
assert(isempty(cfg.interruption.randomSeed) || ...
    (isnumeric(cfg.interruption.randomSeed) && isscalar(cfg.interruption.randomSeed) ...
    && isfinite(cfg.interruption.randomSeed) && cfg.interruption.randomSeed >= 0 ...
    && mod(cfg.interruption.randomSeed, 1) == 0), ...
    'cfg.interruption.randomSeed 必须为空或非负整数。');
if strcmp(modeName, 'random_gap')
    assert(cfg.interruption.numSegments >= 2, ...
        'random_gap 模式至少需要 2 段保留数据。');
end

assert(cfg.iteration.J > 0, 'cfg.iteration.J 必须大于 0。');

assert(islogical(cfg.display.showInterruptedEcho) && isscalar(cfg.display.showInterruptedEcho), ...
    'cfg.display.showInterruptedEcho 必须是逻辑标量。');
assert(islogical(cfg.display.showProgress) && isscalar(cfg.display.showProgress), ...
    'cfg.display.showProgress 必须是逻辑标量。');
assert(cfg.display.progressScale > 0, 'cfg.display.progressScale 必须为正值。');
assert(cfg.display.outputScale > 0, 'cfg.display.outputScale 必须为正值。');
assert(cfg.display.progressUpdateInterval >= 1 && mod(cfg.display.progressUpdateInterval, 1) == 0, ...
    'cfg.display.progressUpdateInterval 必须是正整数。');

assert(ischar(cfg.output.outputDirName) || isstring(cfg.output.outputDirName), ...
    'cfg.output.outputDirName 必须是文本。');
assert(ischar(cfg.output.filePrefix) || isstring(cfg.output.filePrefix), ...
    'cfg.output.filePrefix 必须是文本。');
assert(islogical(cfg.output.separateRunFolder) && isscalar(cfg.output.separateRunFolder), ...
    'cfg.output.separateRunFolder 必须是逻辑标量。');
assert(ischar(cfg.output.runFolderPrefix) || isstring(cfg.output.runFolderPrefix), ...
    'cfg.output.runFolderPrefix 必须是文本。');
assert(ischar(cfg.output.runFolderTimestampFormat) || isstring(cfg.output.runFolderTimestampFormat), ...
    'cfg.output.runFolderTimestampFormat 必须是文本。');
assert(islogical(cfg.output.appendTimestamp) && isscalar(cfg.output.appendTimestamp), ...
    'cfg.output.appendTimestamp 必须是逻辑标量。');
assert(ischar(cfg.output.timestampFormat) || isstring(cfg.output.timestampFormat), ...
    'cfg.output.timestampFormat 必须是文本。');
assert(islogical(cfg.output.savePointAnalysisMat) && isscalar(cfg.output.savePointAnalysisMat), ...
    'cfg.output.savePointAnalysisMat 必须是逻辑标量。');
assert(islogical(cfg.output.savePointAnalysisText) && isscalar(cfg.output.savePointAnalysisText), ...
    'cfg.output.savePointAnalysisText 必须是逻辑标量。');
assert(islogical(cfg.output.savePointAnalysisImage) && isscalar(cfg.output.savePointAnalysisImage), ...
    'cfg.output.savePointAnalysisImage 必须是逻辑标量。');
assert(islogical(cfg.output.saveInterruptionText) && isscalar(cfg.output.saveInterruptionText), ...
    'cfg.output.saveInterruptionText 必须是逻辑标量。');
assert(islogical(cfg.output.saveInterruptionImage) && isscalar(cfg.output.saveInterruptionImage), ...
    'cfg.output.saveInterruptionImage 必须是逻辑标量。');

assert(iscell(cfg.path.dataRootCandidates) && ~isempty(cfg.path.dataRootCandidates), ...
    'cfg.path.dataRootCandidates 必须是非空单元数组。');
for i = 1:numel(cfg.path.dataRootCandidates)
    item = cfg.path.dataRootCandidates{i};
    assert(ischar(item) || isstring(item), ...
        'cfg.path.dataRootCandidates 的每一项都必须是文本。');
end

assert(islogical(cfg.analysis.enablePointAnalysis) && isscalar(cfg.analysis.enablePointAnalysis), ...
    'cfg.analysis.enablePointAnalysis 必须是逻辑标量。');
assert(islogical(cfg.analysis.failOnPointAnalysisError) && isscalar(cfg.analysis.failOnPointAnalysisError), ...
    'cfg.analysis.failOnPointAnalysisError 必须是逻辑标量。');

if ~isempty(cfg.analysis.physics.Br)
    assert(isnumeric(cfg.analysis.physics.Br) && isscalar(cfg.analysis.physics.Br) && cfg.analysis.physics.Br > 0, ...
        'cfg.analysis.physics.Br 必须为空或正值。');
end
if ~isempty(cfg.analysis.physics.Fr)
    assert(isnumeric(cfg.analysis.physics.Fr) && isscalar(cfg.analysis.physics.Fr) && cfg.analysis.physics.Fr > 0, ...
        'cfg.analysis.physics.Fr 必须为空或正值。');
end
if ~isempty(cfg.analysis.physics.PRF)
    assert(isnumeric(cfg.analysis.physics.PRF) && isscalar(cfg.analysis.physics.PRF) && cfg.analysis.physics.PRF > 0, ...
        'cfg.analysis.physics.PRF 必须为空或正值。');
end
assert(isnumeric(cfg.analysis.physics.vc) && isscalar(cfg.analysis.physics.vc) && cfg.analysis.physics.vc > 0, ...
    'cfg.analysis.physics.vc 必须为正值。');
assert(isnumeric(cfg.analysis.physics.squintAngleDeg) && isscalar(cfg.analysis.physics.squintAngleDeg), ...
    'cfg.analysis.physics.squintAngleDeg 必须是数值。');
if ~isempty(cfg.analysis.physics.lambda)
    assert(isnumeric(cfg.analysis.physics.lambda) && isscalar(cfg.analysis.physics.lambda) ...
        && cfg.analysis.physics.lambda > 0, ...
        'cfg.analysis.physics.lambda 必须为空或正值。');
end

assert(islogical(cfg.analysis.autoDerivePRFFromTrack) && isscalar(cfg.analysis.autoDerivePRFFromTrack), ...
    'cfg.analysis.autoDerivePRFFromTrack 必须是逻辑标量。');
assert(isnumeric(cfg.analysis.defaultPRF) && isscalar(cfg.analysis.defaultPRF) && cfg.analysis.defaultPRF > 0, ...
    'cfg.analysis.defaultPRF 必须为正值。');
assert(isstruct(cfg.analysis.pointAnaCfg), 'cfg.analysis.pointAnaCfg 必须是结构体。');
assert(islogical(cfg.analysis.pointAnaCfg.showFigures) && isscalar(cfg.analysis.pointAnaCfg.showFigures), ...
    'cfg.analysis.pointAnaCfg.showFigures 必须是逻辑标量。');
assert(islogical(cfg.analysis.pointAnaCfg.enableTiltAlign) && isscalar(cfg.analysis.pointAnaCfg.enableTiltAlign), ...
    'cfg.analysis.pointAnaCfg.enableTiltAlign 必须是逻辑标量。');
assert(isnumeric(cfg.analysis.pointAnaCfg.tiltApplyThresholdDeg) ...
    && isscalar(cfg.analysis.pointAnaCfg.tiltApplyThresholdDeg) ...
    && isfinite(cfg.analysis.pointAnaCfg.tiltApplyThresholdDeg) ...
    && cfg.analysis.pointAnaCfg.tiltApplyThresholdDeg >= 0, ...
    'cfg.analysis.pointAnaCfg.tiltApplyThresholdDeg 必须是不小于 0 的数值。');
assert(isnumeric(cfg.analysis.pointAnaCfg.tiltEdgeFraction) ...
    && isscalar(cfg.analysis.pointAnaCfg.tiltEdgeFraction) ...
    && isfinite(cfg.analysis.pointAnaCfg.tiltEdgeFraction) ...
    && cfg.analysis.pointAnaCfg.tiltEdgeFraction > 0 ...
    && cfg.analysis.pointAnaCfg.tiltEdgeFraction < 0.5, ...
    'cfg.analysis.pointAnaCfg.tiltEdgeFraction 必须位于 (0, 0.5) 之间。');
end
