function cfg = bp_validate_config(cfg)
%BP_VALIDATE_CONFIG Validate runtime configuration.

assert(islogical(cfg.general.useSinglePrecision) && isscalar(cfg.general.useSinglePrecision), ...
    'cfg.general.useSinglePrecision must be a logical scalar.');
assert(isnumeric(cfg.general.numDataFiles) && isscalar(cfg.general.numDataFiles) ...
    && cfg.general.numDataFiles >= 1 && mod(cfg.general.numDataFiles, 1) == 0, ...
    'cfg.general.numDataFiles must be a positive integer.');
assert(ischar(cfg.general.dataFilePattern) || isstring(cfg.general.dataFilePattern), ...
    'cfg.general.dataFilePattern must be text.');

assert(cfg.radar.c > 0 && cfg.radar.w0 > 0 && cfg.radar.tau > 0, ...
    'cfg.radar.c / w0 / tau must be positive.');
assert(cfg.radar.rangeUpsampleFactor >= 1 && mod(cfg.radar.rangeUpsampleFactor, 1) == 0, ...
    'cfg.radar.rangeUpsampleFactor must be an integer >= 1.');

assert(cfg.image.numPixels >= 2 && mod(cfg.image.numPixels, 1) == 0, ...
    'cfg.image.numPixels must be an integer >= 2.');
assert(isnumeric(cfg.image.xLimits) && numel(cfg.image.xLimits) == 2 ...
    && cfg.image.xLimits(1) < cfg.image.xLimits(2), ...
    'cfg.image.xLimits must be an increasing 2-element numeric vector.');
assert(isnumeric(cfg.image.yLimits) && numel(cfg.image.yLimits) == 2 ...
    && cfg.image.yLimits(1) < cfg.image.yLimits(2), ...
    'cfg.image.yLimits must be an increasing 2-element numeric vector.');

assert(ischar(cfg.interruption.mode) || isstring(cfg.interruption.mode), ...
    'cfg.interruption.mode must be text.');
modeName = char(string(cfg.interruption.mode));
assert(any(strcmp(modeName, {'tail_gap', 'random_gap'})), ...
    'cfg.interruption.mode must be tail_gap or random_gap.');
assert(cfg.interruption.numSegments >= 1 && mod(cfg.interruption.numSegments, 1) == 0, ...
    'cfg.interruption.numSegments must be a positive integer.');
assert(cfg.interruption.missingRatio >= 0 && cfg.interruption.missingRatio < 1, ...
    'cfg.interruption.missingRatio must satisfy 0 <= missingRatio < 1.');
assert(isnumeric(cfg.interruption.gapMinMeters) && isscalar(cfg.interruption.gapMinMeters) ...
    && cfg.interruption.gapMinMeters >= 0, ...
    'cfg.interruption.gapMinMeters must be a nonnegative scalar.');
assert(isnumeric(cfg.interruption.gapMaxMeters) && isscalar(cfg.interruption.gapMaxMeters) ...
    && cfg.interruption.gapMaxMeters >= 0, ...
    'cfg.interruption.gapMaxMeters must be a nonnegative scalar.');
assert(isempty(cfg.interruption.randomSeed) || ...
    (isnumeric(cfg.interruption.randomSeed) && isscalar(cfg.interruption.randomSeed) ...
    && isfinite(cfg.interruption.randomSeed) && cfg.interruption.randomSeed >= 0 ...
    && mod(cfg.interruption.randomSeed, 1) == 0), ...
    'cfg.interruption.randomSeed must be empty or a nonnegative integer.');
if strcmp(modeName, 'random_gap')
    assert(cfg.interruption.numSegments >= 2, ...
        'random_gap requires at least two kept segments.');
end

assert(cfg.iteration.J > 0, 'cfg.iteration.J must be greater than 0.');

assert(islogical(cfg.display.showInterruptedEcho) && isscalar(cfg.display.showInterruptedEcho), ...
    'cfg.display.showInterruptedEcho must be a logical scalar.');
assert(islogical(cfg.display.showProgress) && isscalar(cfg.display.showProgress), ...
    'cfg.display.showProgress must be a logical scalar.');
assert(cfg.display.progressScale > 0, 'cfg.display.progressScale must be positive.');
assert(cfg.display.outputScale > 0, 'cfg.display.outputScale must be positive.');
assert(cfg.display.progressUpdateInterval >= 1 && mod(cfg.display.progressUpdateInterval, 1) == 0, ...
    'cfg.display.progressUpdateInterval must be a positive integer.');

assert(ischar(cfg.output.outputDirName) || isstring(cfg.output.outputDirName), ...
    'cfg.output.outputDirName must be text.');
assert(ischar(cfg.output.filePrefix) || isstring(cfg.output.filePrefix), ...
    'cfg.output.filePrefix must be text.');
assert(islogical(cfg.output.separateRunFolder) && isscalar(cfg.output.separateRunFolder), ...
    'cfg.output.separateRunFolder must be a logical scalar.');
assert(ischar(cfg.output.runFolderPrefix) || isstring(cfg.output.runFolderPrefix), ...
    'cfg.output.runFolderPrefix must be text.');
assert(ischar(cfg.output.runFolderTimestampFormat) || isstring(cfg.output.runFolderTimestampFormat), ...
    'cfg.output.runFolderTimestampFormat must be text.');
assert(islogical(cfg.output.appendTimestamp) && isscalar(cfg.output.appendTimestamp), ...
    'cfg.output.appendTimestamp must be a logical scalar.');
assert(ischar(cfg.output.timestampFormat) || isstring(cfg.output.timestampFormat), ...
    'cfg.output.timestampFormat must be text.');
assert(islogical(cfg.output.savePointAnalysisMat) && isscalar(cfg.output.savePointAnalysisMat), ...
    'cfg.output.savePointAnalysisMat must be a logical scalar.');
assert(islogical(cfg.output.savePointAnalysisText) && isscalar(cfg.output.savePointAnalysisText), ...
    'cfg.output.savePointAnalysisText must be a logical scalar.');
assert(islogical(cfg.output.savePointAnalysisImage) && isscalar(cfg.output.savePointAnalysisImage), ...
    'cfg.output.savePointAnalysisImage must be a logical scalar.');

assert(iscell(cfg.path.dataRootCandidates) && ~isempty(cfg.path.dataRootCandidates), ...
    'cfg.path.dataRootCandidates must be a non-empty cell array.');
for i = 1:numel(cfg.path.dataRootCandidates)
    item = cfg.path.dataRootCandidates{i};
    assert(ischar(item) || isstring(item), ...
        'Each cfg.path.dataRootCandidates entry must be text.');
end

assert(islogical(cfg.analysis.enablePointAnalysis) && isscalar(cfg.analysis.enablePointAnalysis), ...
    'cfg.analysis.enablePointAnalysis must be a logical scalar.');
assert(islogical(cfg.analysis.failOnPointAnalysisError) && isscalar(cfg.analysis.failOnPointAnalysisError), ...
    'cfg.analysis.failOnPointAnalysisError must be a logical scalar.');

if ~isempty(cfg.analysis.physics.Br)
    assert(isnumeric(cfg.analysis.physics.Br) && isscalar(cfg.analysis.physics.Br) && cfg.analysis.physics.Br > 0, ...
        'cfg.analysis.physics.Br must be empty or positive.');
end
if ~isempty(cfg.analysis.physics.Fr)
    assert(isnumeric(cfg.analysis.physics.Fr) && isscalar(cfg.analysis.physics.Fr) && cfg.analysis.physics.Fr > 0, ...
        'cfg.analysis.physics.Fr must be empty or positive.');
end
if ~isempty(cfg.analysis.physics.PRF)
    assert(isnumeric(cfg.analysis.physics.PRF) && isscalar(cfg.analysis.physics.PRF) && cfg.analysis.physics.PRF > 0, ...
        'cfg.analysis.physics.PRF must be empty or positive.');
end
assert(isnumeric(cfg.analysis.physics.vc) && isscalar(cfg.analysis.physics.vc) && cfg.analysis.physics.vc > 0, ...
    'cfg.analysis.physics.vc must be positive.');
assert(isnumeric(cfg.analysis.physics.squintAngleDeg) && isscalar(cfg.analysis.physics.squintAngleDeg), ...
    'cfg.analysis.physics.squintAngleDeg must be numeric.');
if ~isempty(cfg.analysis.physics.lambda)
    assert(isnumeric(cfg.analysis.physics.lambda) && isscalar(cfg.analysis.physics.lambda) ...
        && cfg.analysis.physics.lambda > 0, ...
        'cfg.analysis.physics.lambda must be empty or positive.');
end

assert(islogical(cfg.analysis.autoDerivePRFFromTrack) && isscalar(cfg.analysis.autoDerivePRFFromTrack), ...
    'cfg.analysis.autoDerivePRFFromTrack must be a logical scalar.');
assert(isnumeric(cfg.analysis.defaultPRF) && isscalar(cfg.analysis.defaultPRF) && cfg.analysis.defaultPRF > 0, ...
    'cfg.analysis.defaultPRF must be positive.');
assert(isstruct(cfg.analysis.pointAnaCfg), 'cfg.analysis.pointAnaCfg must be a struct.');
end
